//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Phonenumber')
export class PhonenumberEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  number: string;

  @Column('bool', { nullable: true })
  isScam: boolean;

  @Column('text', { nullable: true })
  description: string;

  @Column('date', { nullable: true })
  dateReported: Date;
}
