//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Report')
export class ReportEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  reporterName: string;

  @Column('text', { nullable: true })
  reportedNumber: string;

  @Column('date', { nullable: true })
  reportedDate: Date;

  @Column('text', { nullable: true })
  reportedDetails: string;

  @Column('text', { nullable: true })
  reportedReason: string;
}
