//Source code generated by AppGPT (www.appgpt.tech)
import { mergeTranslations } from 'ra-core';
import polyglotI18nProvider from 'ra-i18n-polyglot';
import enOriginal from 'ra-language-english';
import frOriginal from 'ra-language-french';
import grOriginal from 'ra-language-greek';

const enResources = {
  resources: {
    Phonenumber: {
      name: 'Phone Number',
      fields: {
        number: 'Number',
        isScam: 'Is Scam',
        description: 'Description',
        dateReported: 'Date Reported',
        id: 'id',
      },
    },
    Report: {
      name: 'Report',
      fields: {
        reporterName: 'Reporter Name',
        reportedNumber: 'Reported Number',
        reportedDate: 'Reported Date',
        reportedDetails: 'Reported Details',
        reportedReason: 'Reported Reason',
        id: 'id',
      },
    },
    User: {
      name: 'User',
      fields: {
        userName: 'User Name',
        email: 'Email',
        password: 'Password',
        phoneNo: 'Phone No',
        registrationDate: 'Registration Date',
        id: 'id',
      },
    },
  },
};
const frResources = {
  resources: {
    Phonenumber: {
      name: 'Phone Number (fr)',
      fields: {
        number: 'Number (fr)',
        isScam: 'Is Scam (fr)',
        description: 'Description (fr)',
        dateReported: 'Date Reported (fr)',
        id: 'id',
      },
    },
    Report: {
      name: 'Report (fr)',
      fields: {
        reporterName: 'Reporter Name (fr)',
        reportedNumber: 'Reported Number (fr)',
        reportedDate: 'Reported Date (fr)',
        reportedDetails: 'Reported Details (fr)',
        reportedReason: 'Reported Reason (fr)',
        id: 'id',
      },
    },
    User: {
      name: 'User (fr)',
      fields: {
        userName: 'User Name (fr)',
        email: 'Email (fr)',
        password: 'Password (fr)',
        phoneNo: 'Phone No (fr)',
        registrationDate: 'Registration Date (fr)',
        id: 'id',
      },
    },
  },
};
const grResources = {
  resources: {
    Phonenumber: {
      name: 'Phone Number (gr)',
      fields: {
        number: 'Number (gr)',
        isScam: 'Is Scam (gr)',
        description: 'Description (gr)',
        dateReported: 'Date Reported (gr)',
        id: 'id',
      },
    },
    Report: {
      name: 'Report (gr)',
      fields: {
        reporterName: 'Reporter Name (gr)',
        reportedNumber: 'Reported Number (gr)',
        reportedDate: 'Reported Date (gr)',
        reportedDetails: 'Reported Details (gr)',
        reportedReason: 'Reported Reason (gr)',
        id: 'id',
      },
    },
    User: {
      name: 'User (gr)',
      fields: {
        userName: 'User Name (gr)',
        email: 'Email (gr)',
        password: 'Password (gr)',
        phoneNo: 'Phone No (gr)',
        registrationDate: 'Registration Date (gr)',
        id: 'id',
      },
    },
  },
};

const en = mergeTranslations(enOriginal, enResources);
const fr = mergeTranslations(frOriginal, frResources);
const gr = mergeTranslations(grOriginal, grResources);

const translations = { en, fr, gr };
export const i18nProvider = polyglotI18nProvider(
  (locale) => translations[locale],
  'en', //default locale
  [
    { locale: 'en', name: 'English' },
    { locale: 'fr', name: 'Français' },
    { locale: 'gr', name: 'Ελληνικά' },
  ],
);
